name: Build, Test and Deploy to Azure

on:
  workflow_dispatch:
  push:
    branches:
    - Service-Bus

env:
  AZURE_WEBAPP_NAME: chatservice-jad-ronald
  AZURE_WEBAPP_PACKAGE_PATH: './publish'
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'
        
    - name: Restore dependencies
      run: dotnet restore ./ChatApplication/ChatApplication.sln
      
    - name: Build
      run: dotnet build ./ChatApplication/ChatApplication.sln --configuration Release --no-restore
        
    - name: Publish
      run: dotnet publish --configuration Release --output '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}' --no-restore ./ChatApplication/ChatApplication.Web
      
    - name: Deploy
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_CHATSERVICE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
